server:
  port: 8889
  tomcat:
    uri-encoding: utf-8

github:
  client:
    id: 25937c33817d0cbfe4ef
    secret: 73e40515a345fc6e0c5fdad4816a5bf88ea82d3a
  redirect:
    uri: http://localhost:8889/callback

#激活配置环境
spring:
  mvc:
    static-path-pattern: /** #能够让springboot识别到static目录下所有的子目录
  profiles:
    active: mysql
  thymeleaf:
    cache: false #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
  redis:
    database: 5
    timeout: 5000
    host: 10.252.1.21
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




---
# h2数据库环境
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:D:/h2/community
    password: sa
    username: 123
    driver-class-name: org.h2.Driver
---
spring:
  flyway:
    enabled: true
    locations: classpath:db/mysql
   # check-location: false
  profiles: mysql
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5